name: setup-nix
description: Set up a Nix environment
inputs:
  cachix-auth-token:
    description: Authentication token for Cachix
    required: true
  cachix-name:
    description: Name of the Cachix cache
    required: false
    default: ponko2
  prefetch-dependencies:
    description: Run `nix --quiet develop --command true` after setup.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
    - name: Set up Cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: ${{ inputs.cachix-name }}
        authToken: ${{ inputs.cachix-auth-token }}
    - name: Prefetch Nix dependencies
      if: ${{ inputs.prefetch-dependencies == 'true' }}
      shell: bash
      run: nix --quiet develop --command true
