[settings]
lockfile = true

[tools]
"npm:@commitlint/cli" = "latest"
actionlint = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
hk = "latest"
oxfmt = "latest"
python = "latest"
shellcheck = "latest"
uv = "latest"
zizmor = "latest"

[tools.yamllint]
version = "latest"
depends = ["python", "uv"]
