name: zizmor
description: Lint GitHub Actions with zizmor
runs:
  using: composite
  steps:
    - name: Run zizmor
      uses: docker://ghcr.io/zizmorcore/zizmor:1.23.1@sha256:a58f658823d78dd38762f1ce44e31265d636bbfb8b1462cef1dfb1af788d3b86
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: -p --format=github --min-severity=low .
