name: zizmor
description: Lint GitHub Actions with zizmor
runs:
  using: composite
  steps:
    - name: Run zizmor
      uses: docker://ghcr.io/zizmorcore/zizmor:1.13.0@sha256:89ccca3a97b41ab335e30c716b9cd7129baab377f8cf0cb1a19d593820d6b0d0
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: -p --format=github --min-severity=low .
