name: zizmor
description: Lint GitHub Actions with zizmor
runs:
  using: composite
  steps:
    - name: Run zizmor
      uses: docker://ghcr.io/zizmorcore/zizmor:1.24.1@sha256:128ebbe369a95f9d4427737e794537256095b55f779a247aebc960dc4ea1f7b3
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: -p --format=github --min-severity=low .
