name: zizmor
description: Lint GitHub Actions with zizmor
runs:
  using: composite
  steps:
    - name: Run zizmor
      uses: docker://ghcr.io/zizmorcore/zizmor:1.16.1@sha256:f4ec2276a32656a82f97cf2d79b02ee7b0e5b2423d0eba167c9ffc4c5e49956a
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: -p --format=github --min-severity=low .
