name: zizmor
description: Lint GitHub Actions with zizmor
runs:
  using: composite
  steps:
    - name: Run zizmor
      uses: docker://ghcr.io/zizmorcore/zizmor:1.16.3@sha256:f09cee55087d54e7a162fc255ffe82ef942f68e683f967c8a6471ffe35e7ec64
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        args: -p --format=github --min-severity=low .
