name: actionlint
description: Lint GitHub Actions with actionlint
runs:
  using: composite
  steps:
    - name: Add problem matchers
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: echo "::add-matcher::${ACTION_PATH}/matcher.json"
    - name: Run actionlint
      uses: docker://rhysd/actionlint:1.7.11@sha256:6f03470d0152251d7f07f7c4dc019dbe7024c72cd952f839544c7798843efa8f
      with:
        args: -color
