name: actionlint
description: Lint GitHub Actions with actionlint
runs:
  using: composite
  steps:
    - name: Add problem matchers
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: echo "::add-matcher::${ACTION_PATH}/matcher.json"
    - name: Run actionlint
      uses: docker://rhysd/actionlint:1.7.8@sha256:96d4a8c87dbbfb3bdd324f8fdc285fc3df5261e2decc619a4dd7e8ee52bbfd46
      with:
        args: -color
