name: actionlint
description: Lint GitHub Actions with actionlint
runs:
  using: composite
  steps:
    - name: Add problem matchers
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: echo "::add-matcher::${ACTION_PATH}/matcher.json"
    - name: Run actionlint
      uses: docker://rhysd/actionlint:1.7.10@sha256:ef8299f97635c4c30e2298f48f30763ab782a4ad2c95b744649439a039421e36
      with:
        args: -color
