name: actionlint
description: Lint GitHub Actions with actionlint
runs:
  using: composite
  steps:
    - name: Add problem matchers
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/matcher.json"
    - name: Run actionlint
      uses: docker://rhysd/actionlint:1.7.7@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9
      with:
        args: -color
